#ifndef CONFIG_B4LTHAZAR_H
#define CONFIG_B4LTHAZAR_H
#include "../../config.h"

#undef  TAPPING_TERM
#define TAPPING_TERM 200

#undef TAPPING_TOGGLE
#define TAPPING_TOGGLE 2

#undef IGNORE_MOD_TAP_INTERRUPT

#endif /* CONFIG_B4LTHAZAR_H */
